version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rds-initialize-user"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1stj2f56tyx8u"
s3_prefix = "rds-initialize-user"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
